WSO2Telco/core-util

components/dbutil/src/main/java/com/wso2telco/dbutils/AxiataDbService.java
components/dbutil/src/main/java/com/wso2telco/dbutils/DbUtils.java
components/dbutil/src/main/java/com/wso2telco/dbutils/Operator.java
components/dbutil/src/main/java/com/wso2telco/dbutils/Operatorendpoint.java
components/dbutil/src/main/java/com/wso2telco/dbutils/Operatorsubs.java
components/dbutil/src/main/java/com/wso2telco/dbutils/fileutils/FileReader.java
components/dbutil/src/main/java/com/wso2telco/dbutils/util/PropertyFileNames.java

Deprecated some db query methods used in mediator.
Deprecated methods moved to the mediator classes.

PRODEV-382

---

components/mi-util/src/main/java/com/wso2telco/core/mi/hibernate/SessionFactoryUtil.java

HUBDEV-671 Fix for the Issue in SessionFactoryUtil class

HUBDEV-671 Fix for the Issue in SessionFactoryUtil

---

components/dbutil/src/main/java/com/wso2telco/core/dbutils/exception/PolicyError.java
components/dbutil/src/main/java/com/wso2telco/core/dbutils/exception/ServiceError.java
components/mi-util/src/main/java/com/wso2telco/core/mi/hibernate/HibernateAbstractDAO.java

HUBDEV-534 Error Handling and save Hibernate Object related improvements

HUBDEV-534 Error Handling and save Hibernate Object related improvements

---

components/msisdn-validator/src/main/java/com/wso2telco/core/msisdnvalidator/MSISDNUtil.java

HUBDEV-587 changes in msisdn module to support all msisdn formats currently in use

HUBDEV-587 changes in msisdn module to support all msisdn formats currently in use

---

components/config-util/src/main/java/com/wso2telco/core/config/model/MobileConnectConfig.java

Public Jira: https://jira.wso2telco.com/jira/browse/IDSDEV-178
This needs to be merged before merging https://github.com/WSO2Telco/component-ids/pull/47

JAXB changes for adding AuthenticatorSelectionConfig to mobile-connect.xml

---

components/config-util/src/main/java/com/wso2telco/core/config/model/MobileConnectConfig.java

This PR adds missing elements in MobileConnectConfig model.
https://github.com/WSO2Telco/component-ids/pull/83 depends on this.

Adding missing SMSConfig elements to MobileConnectConfig model

---

components/config-util/src/main/java/com/wso2telco/core/config/model/MobileConnectConfig.java

https://github.com/WSO2Telco/component-ids/pull/141 depends on this PR.

Adding SMS timeout config element to MobileConnectConfig

---

components/config-util/src/main/java/com/wso2telco/core/config/model/MobileConnectConfig.java

https://jira.wso2telco.com/jira/browse/IDSDEV-467

Correcting accesstoken annotation

---

components/dbutil/src/main/java/com/wso2telco/core/dbutils/exception/ServiceError.java

Add changes to the ServiceError

HUBDEV-1728

---

components/config-util/src/main/java/com/wso2telco/core/config/model/MobileConnectConfig.java

Reverts WSO2Telco/core-util#111

Revert "IDSDEV-639 : Language config read from m-c.xml"

---

components/auth-filter/pom.xml
components/auth-filter/src/main/java/com/wso2telco/core/authfilter/BasicAuthenticationFilter.java
components/auth-filter/src/main/java/com/wso2telco/core/authfilter/authentication/BasicAuthenticator.java
components/auth-filter/src/main/java/com/wso2telco/core/authfilter/authorization/UserAuthorizationValidator.java
components/auth-filter/src/test/java/com/wso2telco/core/AppTest.java
pom.xml

Implement auth-filter for handle authentication in REST services

HUBDEV-1783

---

components/security/user-profile/src/main/java/com/wso2telco/core/userprofile/permission/impl/UserRolePermissionFactory.java

bugfix for DEPAM-342, Merging the patch 00056 to master

Merging the patch 00056 to master

---

components/dbutil/src/main/java/com/wso2telco/core/dbutils/exception/BusinessException.java
components/security/auth-filter/pom.xml
components/security/auth-filter/src/main/java/com/wso2telco/core/authfilter/authentication/BearerAuthenticator.java
components/security/auth-filter/src/main/java/com/wso2telco/core/authfilter/authorization/UserAuthorizationValidator.java
components/security/auth-filter/src/main/java/com/wso2telco/core/authfilter/impl/authorization/AuthorizationFilterFactory.java
components/security/auth-filter/src/main/java/com/wso2telco/core/authfilter/impl/authorization/BasicAuthenticationFilter.java
components/security/auth-filter/src/main/java/com/wso2telco/core/authfilter/impl/authorization/BearerAuthenticationFilter.java
components/security/auth-filter/src/main/java/com/wso2telco/core/authfilter/util/AuthFilterParam.java
components/security/user-profile/src/main/java/com/wso2telco/core/userprofile/permission/impl/UserRolePermissionFactory.java
components/security/user-profile/src/main/java/com/wso2telco/core/userprofile/permission/impl/WSO2PermissionBuilder.java

Merge all changes from the patches

Egw upgrade lift(Changes merged from patch branches)

---

components/sp-config-util/src/main/java/com/wso2telco/core/sp/config/utils/dao/impl/SpConfigDAOImpl.java

try with resources used instead of finally blocks

[INTGW-777] SonarQube reported issue fixing

---

components/security/user-profile/src/main/java/com/wso2telco/core/userprofile/prosser/UserRoleProsser.java

useless assignments are removed

[INTGW-778] SonarQube reported issue fixing

---

components/security/user-profile/src/main/java/com/wso2telco/core/userprofile/prosser/UserClaimProsser.java

[INTGW-779] SonarQube reported issue fixing

---

components/pcr-service/src/main/java/com/wso2telco/core/pcrservice/util/SectorUtil.java

[INTGW-780] SonarQube reported issue fixing

---

components/pcr-service/src/main/java/com/wso2telco/core/pcrservice/util/RedisUtil.java

Remove the "volatile" keyword from Non-primitive fields

[INTGW-781] SonarQube reported issue fixing

---

components/msisdn-validator/src/main/java/com/wso2telco/core/msisdnvalidator/MSISDNUtil.java

Null pointer dereferenced issue fixed

[INTGW-782] SonarQube reported issue fixing

---

components/security/user-profile/src/main/java/com/wso2telco/core/userprofile/permission/impl/UserRolePermissionFactory.java

https://jira.wso2telco.com/jira/browse/EXTGW-442

EXTGW-442 - [EGW] Manage service Error while loading application & subscription list
